version: "3.0"
services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=goTaskFlow
      - POSTGRES_USER=goTaskFlow
      - POSTGRES_PASSWORD=password

