app_name: cron
env: dev
server:
  host: localhost
  port: 8086
logger:
  level: 1   
temporal:
  host: localhost
  port: 7233
  cron_worker_queue: TASK_WORKER_QUEUE

database:
  name: goTaskFlow
  user: goTaskFlow
  password: password
  port: 5432
  host: localhost
  timeout: 60
mailer:
  host: "smtp.gmail.com"
  port: 587
  from : "bipen.c@gopherslab.com"
  username: bipen.c@gopherslab.com
  password: apandhgfsewpptro